server:
  files-destination-dir: src/main/resources/files/
  port: 8000



spring:
  servlet:
    multipart:
      max-file-size: 2000KB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true


jwt:
  secret: KrcPHZWVqWGWtDVyT8Ky5CZmDJnpBJkan1hQkMCI
  expiration-time: 86400