spring:
  servlet:
    multipart:
      max-file-size: 500KB

  datasource:
    url: jdbc:h2:mem:default
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create

redis:
  hostname: localhost
  port: 6379