server:
  files-destination-dir: src/main/resources/files/

spring:
  servlet:
    multipart:
      max-file-size: 2000KB
  datasource:
    url: jdbc:h2:mem:default
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update