server:
  port: 8000

aws:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  region: ${S3_REGION}
  url: ${S3_URL}
  bucket-name: ${S3_BUCKET_NAME}

  users-root-directory: events-platform-files/test/users
  posts-root-directory: events-platform-files/test/posts
  default-post-avatar-dir: events-platform-files/default/default-post-avatar.jpg
  default-avatar-dir: events-platform-files/default/default-avatar.jpg

spring:
  servlet:
    multipart:
      max-file-size: 500KB

  datasource:
    url: jdbc:h2:mem:default
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create

redis:
  hostname: localhost
  port: 6379

jwt:
  access-secret: ${random.uuid}
  refresh-secret: ${random.uuid}
  access-token-expiration-time: 86400 # In seconds
  refresh-token-expiration-time: 2629800000 # In seconds