server:
  port: 8000
  files-destination-dir: users_files/
  default-avatar-dir: templates/avatar.jpg

spring:
  servlet:
    multipart:
      max-file-size: 1000KB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://80.90.189.25:5432/nobodyknowsdotcomdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true

redis:
  hostname: redis
  port: 6379

jwt:
  access-secret: KrcPHZWVqWGWtDVyT8Ky5CZmDJnpBJkan1hQkMCI
  refresh-secret: Zmsoal13nvWD8VWhpS3J4mbClOzR5vTxdk17xXbt
  access-token-expiration-time: 86400 # In seconds
  refresh-token-expiration-time: 2629800000 # In seconds