server:
  port: 8000

aws:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  region: ${S3_REGION}
  url: ${S3_URL}
  bucket-name: ${S3_BUCKET_NAME}

  users-root-directory: events-platform-files/test/users
  posts-root-directory: events-platform-files/test/posts
  default-post-avatar-dir: events-platform-files/default/default-post-avatar.jpg
  default-avatar-dir: events-platform-files/default/default-avatar.jpg


spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  data:
    web:
      pageable:
        max-page-size: 30
  servlet:
    multipart:
      max-file-size: 3500KB

jwt:
  access-secret: super-static-secret-string-42-foo-bar-baz
  refresh-secret: super-static-secret-string-42-foo-bar-baz
  access-token-expiration-time: 86400 # In seconds
  refresh-token-expiration-time: 2629800000 # In seconds