server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      mode: always


jwt:
  secret: KrcPHZWVqWGWtDVyT8Ky5CZmDJnpBJkan1hQkMCI
  expiration-time: 86400