server:
  port: 8000

aws:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  region: ${S3_REGION}
  url: ${S3_URL}
  bucket-name: ${S3_BUCKET_NAME}

  users-root-directory: events-platform-files/test/users
  posts-root-directory: events-platform-files/test/posts
  default-post-avatar-dir: events-platform-files/default/default-post-avatar.jpg
  default-avatar-dir: events-platform-files/default/default-avatar.jpg


spring:
  servlet:
    multipart:
      max-file-size: 500KB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true

redis:
  hostname: localhost
  port: 6379

jwt:
  access-secret: super-static-secret-string-42-foo-bar-baz
  refresh-secret: super-static-secret-string-42-foo-bar-baz
  access-token-expiration-time: 86400 # In seconds
  refresh-token-expiration-time: 2629800000 # In seconds