version: "3.3"

services:
  app:
    image: 'nobodyknowsdotcom/events-platform-backend:latest'
    container_name: backend
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME
      - DB_PASSWORD
  redis:
    image: "redis/redis-stack-server"
    container_name: redis