version: "3.3"

services:
  app:
    image: 'nobodyknowsdotcom/events-platform-backend:0.0.82'
    container_name: backend
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_NAME
  redis:
    image: "redis/redis-stack-server"
    container_name: redis