version: "3.3"

services:
  app:
    image: 'nobodyknowsdotcom/events-platform-backend:0.0.85'
    container_name: app
    ports:
      - ${APP_PORT}:8000
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION}
      S3_URL: ${S3_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      APP_PORT: ${APP_PORT}
  redis:
    image: "redis/redis-stack-server"
    container_name: redis