name: CI/CD main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Build with Gradle
      run: |
          ./gradlew clean build
  
    - id : project_version
      name : Retrieve Version
      run: |
        echo "::set-output name=VERSION_NAME::$(./gradlew printVersionName)"
    
    - name: Get version
      run: |
        echo "version_name=${{steps.project_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
      
    - name: Test
      run: echo $VERSION_NAME
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: nobodyknowsdotcom/events-plarform-backend:"${{env.VERSION_NAME}}"
