name: CI/CD main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Build with Gradle
      run: |
          ./gradlew clean buildDocker
          
    - name: Get the version
      id: vars
      run: echo "::set-output name=VERSION_NAME::$(./gradlew printVersionName)"
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run : docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.io
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.BACKEND_REPO_NAME}}:${{steps.vars.outputs.VERSION_NAME}}
    - name: Publish dockerimage to docker hub
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.BACKEND_REPO_NAME}}:${{steps.vars.outputs.VERSION_NAME}}

